In [1]:
import pandas as pd
import plotly.express as px

In [ ]:
acc_data = pd.read_csv("acc_data_rblc_0410_2.csv")
ecg_data = pd.read_csv("ecg_data_rblc_0410_2.csv")

In [3]:
acc_data

          time        t_wall         t_device_ns    x    y    z
0     0.000000  1.775806e+09  599619408462370584 -974  118  280
1     0.005000  1.775806e+09  599619408462370584 -973  117  279
2     0.010000  1.775806e+09  599619408462370584 -977  118  280
3     0.015000  1.775806e+09  599619408462370584 -974  116  276
4     0.020000  1.775806e+09  599619408462370584 -970  116  281
...        ...           ...                 ...  ...  ...  ...
1003  4.909827  1.775806e+09  599619413217197056 -973  119  270
1004  4.914827  1.775806e+09  599619413217197056 -974  119  272
1005  4.919827  1.775806e+09  599619413217197056 -970  117  274
1006  4.924827  1.775806e+09  599619413217197056 -971  118  275
1007  4.929826  1.775806e+09  599619413217197056 -971  118  275

[1008 rows x 6 columns]

In [4]:
px.line(acc_data,
        x = "time",
        y = ["x", "y", "z"],
        title = "Accelerometer data")

In [5]:
ecg_data

         time        t_wall         t_device_ns   ecg
0    0.000000  1.775806e+09  599619408963262552 -1350
1    0.007692  1.775806e+09  599619408963262552 -1491
2    0.015385  1.775806e+09  599619408963262552 -1622
3    0.023077  1.775806e+09  599619408963262552 -1750
4    0.030769  1.775806e+09  599619408963262552 -1874
..        ...           ...                 ...   ...
652  5.015998  1.775806e+09  599619413456183548   -15
653  5.023690  1.775806e+09  599619413456183548   -31
654  5.031382  1.775806e+09  599619413456183548   -63
655  5.039075  1.775806e+09  599619413456183548  -117
656  5.046767  1.775806e+09  599619413456183548  -180

[657 rows x 4 columns]

In [6]:
px.line(ecg_data,
        x = "time",
        y = "ecg",
        title = "ECG data (Voxel wet fur)")