In [75]:
import pandas as pd

In [76]:
acc_df = pd.read_csv("/Users/rblc/create/work/elte/polar/data/acc.csv")
ecg_df = pd.read_csv("/Users/rblc/create/work/elte/polar/data/ecg.csv")

In [80]:
acc_df.columns

Index(['packet_id', 'device_time', 'host_time', 'x', 'y', 'z'], dtype='str')

In [81]:
acc_df.head()

   packet_id   device_time     host_time   x   y     z
0          0  5.996174e+11  1.780931e+12 -78  97 -1027
1          0  5.996174e+11  1.780931e+12 -85  96 -1025
2          0  5.996174e+11  1.780931e+12 -84  97 -1023
3          0  5.996174e+11  1.780931e+12 -84  97 -1024
4          0  5.996174e+11  1.780931e+12 -85  97 -1021

In [82]:
ACC_DT = 1 / 200
ACC_DT_MS = ACC_DT * 1000

acc_df["sample_idx"] = acc_df.groupby("packet_id").cumcount()
packet_sizes = acc_df.groupby("packet_id")["packet_id"].transform("size")

acc_df["sample_time"] = (
    acc_df["device_time"]
    - ((packet_sizes - 1 - acc_df["sample_idx"]) * ACC_DT_MS)
)

acc_df["time_ms"] = acc_df["sample_time"] - acc_df["sample_time"].min()

In [84]:
packet_sizes

0      36
1      36
2      36
3      36
4      36
       ..
967    36
968    36
969    36
970    36
971    36
Name: packet_id, Length: 972, dtype: int64

In [83]:
acc_df

,packet_id,device_time,host_time,x,y,z,sample_idx,sample_time,time_ms
0,0,5.996174e+11,1.780931e+12,-78,97,-1027,0,5.996174e+11,0.000000
1,0,5.996174e+11,1.780931e+12,-85,96,-1025,1,5.996174e+11,5.000000
2,0,5.996174e+11,1.780931e+12,-84,97,-1023,2,5.996174e+11,10.000000
3,0,5.996174e+11,1.780931e+12,-84,97,-1024,3,5.996174e+11,15.000000
4,0,5.996174e+11,1.780931e+12,-85,97,-1021,4,5.996174e+11,20.000000
...,...,...,...,...,...,...,...,...,...
967,26,5.996174e+11,1.780931e+12,-85,95,-1025,31,5.996174e+11,4884.038696
968,26,5.996174e+11,1.780931e+12,-87,94,-1022,32,5.996174e+11,4889.038696
969,26,5.996174e+11,1.780931e+12,-87,93,-1023,33,5.996174e+11,4894.038696
970,26,5.996174e+11,1.780931e+12,-85,95,-1018,34,5.996174e+11,4899.038696
971,26,5.996174e+11,1.780931e+12,-89,96,-1018,35,5.996174e+11,4904.038696

In [ ]:
ECG_DT = 1 / 130
ECG_DT_MS = ECG_DT * 1000

ecg_df["sample_idx"] = ecg_df.groupby("packet_id").cumcount()
packet_sizes = ecg_df.groupby("packet_id")["packet_id"].transform("size")

ecg_df["sample_time"] = (
    ecg_df["device_time"]
    - ((packet_sizes - 1 - ecg_df["sample_idx"]) * ECG_DT_MS)
)

ecg_df["time_ms"] = ecg_df["sample_time"] - ecg_df["sample_time"].min()